# Generated by Django 5.0 on 2023-12-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_livros_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='empretado',
            new_name='emprestado',
        ),
    ]
